(function () {
  function parseTranscriptXml(xmlText) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(xmlText, "text/xml");
    const textNodes = doc.querySelectorAll("text");
    
    if (!textNodes.length) return "";
    
    const lines = [];
    textNodes.forEach((node) => {
      const text = node.textContent.trim();
      if (text) {
        const decoded = text
          .replace(/&amp;/g, "&")
          .replace(/&lt;/g, "<")
          .replace(/&gt;/g, ">")
          .replace(/&quot;/g, '"')
          .replace(/&#39;/g, "'")
          .replace(/\n/g, " ");
        lines.push(decoded);
      }
    });
    
    return lines.join("\n");
  }

  function findCaptionTracks() {
    try {
      const scriptTags = document.querySelectorAll("script");
      for (const script of scriptTags) {
        const content = script.textContent || "";
        if (!content.includes("captionTracks")) continue;
        
        const match = content.match(/["']captionTracks["']\s*:\s*(\[.*?\])/);
        if (!match) continue;
        
        try {
          const tracks = JSON.parse(match[1]);
          if (Array.isArray(tracks) && tracks.length > 0) {
            return tracks;
          }
        } catch (parseError) {
          continue;
        }
      }
      
      if (window.ytInitialPlayerResponse && window.ytInitialPlayerResponse.captions) {
        const captionsData = window.ytInitialPlayerResponse.captions;
        if (captionsData.playerCaptionsTracklistRenderer && captionsData.playerCaptionsTracklistRenderer.captionTracks) {
          return captionsData.playerCaptionsTracklistRenderer.captionTracks;
        }
      }
    } catch (error) {
      console.warn("Error finding caption tracks:", error);
    }
    return null;
  }

  function selectBestTrack(tracks) {
    if (!tracks || !tracks.length) return null;
    
    const english = tracks.find((track) => {
      const lang = (track.languageCode || "").toLowerCase();
      return lang === "en" || lang.startsWith("en-");
    });
    if (english) return english;
    
    const notAsr = tracks.find((track) => track.kind !== "asr");
    if (notAsr) return notAsr;
    
    return tracks[0];
  }

  async function fetchTranscriptXml(track) {
    if (!track || !track.baseUrl) {
      throw new Error("Invalid transcript track");
    }
    
    const response = await fetch(track.baseUrl);
    if (!response.ok) {
      throw new Error(`Failed to fetch transcript: ${response.status}`);
    }
    
    return await response.text();
  }

  async function extractTranscript(videoId) {
    const tracks = findCaptionTracks();
    
    if (!tracks || !tracks.length) {
      throw new Error("No transcript available for this video");
    }
    
    const selectedTrack = selectBestTrack(tracks);
    if (!selectedTrack) {
      throw new Error("Could not select a transcript track");
    }
    
    const xmlText = await fetchTranscriptXml(selectedTrack);
    const transcript = parseTranscriptXml(xmlText);
    
    if (!transcript) {
      throw new Error("Failed to parse transcript");
    }
    
    return {
      text: transcript,
      language: selectedTrack.languageCode || "unknown",
      isAutoGenerated: selectedTrack.kind === "asr"
    };
  }

  async function checkTranscriptAvailable() {
    const tracks = findCaptionTracks();
    return tracks && tracks.length > 0;
  }

  window.IgBulkYouTubeTranscript = {
    extractTranscript,
    checkTranscriptAvailable
  };
})();
